sudo: required

services:
  - docker

language: go
go: 1.6

env:
  - IMAGE_NAME=rust-s2i RUNTIME_IMAGE_NAME=rust-s2i-runtime S2I_BINARY="https://github.com/openshift/source-to-image/releases/download/v1.1.3/source-to-image-v1.1.3-ddb10f1-linux-amd64.tar.gz"

install:
  - mkdir -p /tmp/s2i
  - "curl -L \"${S2I_BINARY}\" > /tmp/s2i/s2i.tar.gz"
  - pushd /tmp/s2i
  - tar -xvf s2i.tar.gz
  - sudo cp s2i /usr/local/bin
  - rm -rf *
  - popd

script:
  - make test
