sudo: required

services:
  - docker

language: go

go: 1.6

env:
  - IMAGE_NAME=rust-s2i S2I_BINARY="https://github.com/openshift/source-to-image/releases/download/v1.1.3/source-to-image-v1.1.3-ddb10f1-darwin-amd64.tar.gz"

install:
  - "curl -L \"${S2I_BINARY}\" > s2i.tar.gz"
  - tar -xvf s2i.tar.gz
  - sudo cp s2i /usr/local/bin
  - rm -rf *

script:
  - docker build -t "${IMAGE_NAME}" .
  - test/run
